version: '3.8'

services:
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/gateway:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  catalog-service:
    build:
      context: ./services/catalog-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/catalog-service:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/auth-service:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  importer-service:
    build:
      context: ./services/importer-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/importer-service:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  recommender-service:
    build:
      context: ./services/recommender-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/recommender-service:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/analytics-service:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  frontend-react:
    build:
      context: ./frontend/react
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend-angular:
    build:
      context: ./frontend/angular
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/angular:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

